import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { regulatoryData } from "@/app/data/regulatory-data";
import { COUNTRY_FRAMES } from "@/app/data/country-frames";
import { COUNTRY_DETAIL } from "@/app/data/country-detail";
import { DIVISION_PROFILES } from "@/app/data/divisions";
import { requirementsForDivision } from "@/app/data/requirements-data";

const W = 960;
const H = 520;

/**
 * country-frames.ts and country-detail.ts are generated by
 * scripts/build-country-detail.mjs and committed. Nothing runs the generator
 * automatically, so the failure mode is silent: add a jurisdiction, forget to
 * regenerate, and the camera falls back to the raw feature bounds — which is
 * exactly the bug the frames exist to fix, and it looks like a design choice
 * rather than a mistake.
 */
describe("map camera geometry", () => {
  it("frames every mapped jurisdiction", () => {
    const missing = Object.values(regulatoryData)
      .filter((c) => !COUNTRY_FRAMES[c.id])
      .map((c) => `${c.name} (${c.id})`);
    expect(missing).toEqual([]);
  });

  it("has a detail outline for every frame", () => {
    for (const id of Object.keys(COUNTRY_FRAMES)) {
      expect(COUNTRY_DETAIL[id], id).toBeTruthy();
    }
  });

  it("frames nothing that is not on the map", () => {
    const orphans = Object.keys(COUNTRY_FRAMES).filter((id) => !regulatoryData[id]);
    expect(orphans).toEqual([]);
  });

  it("keeps every frame inside the projection", () => {
    for (const [id, [x, y, w, h]] of Object.entries(COUNTRY_FRAMES)) {
      expect(w, id).toBeGreaterThan(0);
      expect(h, id).toBeGreaterThan(0);
      expect(x, id).toBeGreaterThanOrEqual(-1);
      expect(y, id).toBeGreaterThanOrEqual(-1);
      expect(x + w, id).toBeLessThanOrEqual(W + 1);
      expect(y + h, id).toBeLessThanOrEqual(H + 1);
    }
  });

  it("frames on principal landmasses, not the whole feature", () => {
    // The United States is the canonical failure: bounded including Alaska and
    // the Aleutians it is 844 of 960 units wide, which leaves the camera
    // nothing to do. Canada, France, Norway and the Netherlands fail the same
    // way. No frame should span more than half the world.
    for (const [id, [, , w]] of Object.entries(COUNTRY_FRAMES)) {
      expect(w, `${id} frame spans ${w} of ${W}`).toBeLessThan(W / 2);
    }
  });

  it("draws only closed subpaths", () => {
    for (const [id, d] of Object.entries(COUNTRY_DETAIL)) {
      expect(d.startsWith("M"), id).toBe(true);
      expect(d.endsWith("Z"), id).toBe(true);
      expect(d.match(/M/g)?.length, id).toBe(d.match(/Z/g)?.length);
    }
  });

  it("puts each detail outline inside its own frame", () => {
    for (const [id, d] of Object.entries(COUNTRY_DETAIL)) {
      const nums = (d.match(/-?\d+(?:\.\d+)?/g) ?? []).map(Number);
      const xs = nums.filter((_, i) => i % 2 === 0);
      const ys = nums.filter((_, i) => i % 2 === 1);
      const [fx, fy, fw, fh] = COUNTRY_FRAMES[id];
      // Half a unit of slack for the rounding the generator applies.
      expect(Math.min(...xs), id).toBeGreaterThanOrEqual(fx - 0.5);
      expect(Math.max(...xs), id).toBeLessThanOrEqual(fx + fw + 0.5);
      expect(Math.min(...ys), id).toBeGreaterThanOrEqual(fy - 0.5);
      expect(Math.max(...ys), id).toBeLessThanOrEqual(fy + fh + 0.5);
    }
  });
});

/**
 * public/data/world-map.json is generated by scripts/build-world-map.mjs.
 *
 * This exists because of a real bug, not a hypothetical one: projecting each
 * coordinate by hand instead of feeding the projection stream skipped
 * antimeridian cutting, and Russia rendered as a copper band straight across
 * the world. Fiji did the same. The failure is invisible to type checking, to
 * the build and to every other test — you only catch it by looking at the map,
 * or by measuring it here.
 */
describe("the projected world", () => {
  const world = JSON.parse(
    readFileSync(join(process.cwd(), "public/data/world-map.json"), "utf8")
  ) as { w: number; h: number; countries: { i: string; n: string; d: string }[] };

  it("covers the countries the map needs", () => {
    expect(world.countries.length).toBeGreaterThan(200);
    for (const id of Object.keys(regulatoryData)) {
      expect(world.countries.some((c) => c.i === id), id).toBe(true);
    }
  });

  it("draws nothing that runs across the map", () => {
    const smears: string[] = [];
    for (const c of world.countries) {
      // Antarctica genuinely spans the bottom edge of the projection.
      if (c.i === "010") continue;
      for (const sub of c.d.split("M").filter(Boolean)) {
        const pts = sub
          .replace("Z", "")
          .split("L")
          .map((t) => t.trim().split(" ").map(Number));
        for (let k = 1; k < pts.length; k++) {
          const dx = Math.abs(pts[k][0] - pts[k - 1][0]);
          if (dx > 250) smears.push(`${c.n} (${c.i}) has a ${dx.toFixed(0)}-unit edge`);
        }
      }
    }
    expect(smears).toEqual([]);
  });

  it("keeps every country inside the projection", () => {
    for (const c of world.countries) {
      const nums = c.d.match(/-?\d+(?:\.\d+)?/g)!.map(Number);
      const xs = nums.filter((_, i) => i % 2 === 0);
      const ys = nums.filter((_, i) => i % 2 === 1);
      expect(Math.min(...xs), c.i).toBeGreaterThanOrEqual(-1);
      expect(Math.max(...xs), c.i).toBeLessThanOrEqual(world.w + 1);
      expect(Math.min(...ys), c.i).toBeGreaterThanOrEqual(-1);
      expect(Math.max(...ys), c.i).toBeLessThanOrEqual(world.h + 1);
    }
  });
});

describe("the standard layer beside a jurisdiction", () => {
  it("has a profile for every division the requirement matrix uses", () => {
    for (const p of DIVISION_PROFILES) {
      expect(requirementsForDivision(p.division).length, `D${p.division}`).toBeGreaterThan(0);
    }
    expect(DIVISION_PROFILES.map((p) => p.division)).toEqual([1, 2, 3, 4, 5]);
  });
});
