import { describe, it, expect } from "vitest";
import { regulatoryData } from "@/app/data/regulatory-data";
import { COUNTRY_SHAPES, COUNTRY_BOUNDS } from "@/app/data/country-shapes";

/**
 * country-shapes.ts is generated by scripts/build-country-shapes.mjs and
 * committed. These tests exist because the generator is the only thing that
 * keeps it in step with regulatory-data.ts, and nothing runs the generator
 * automatically. Add a jurisdiction, forget to regenerate, and the failure is
 * silent: the map still zooms, the page still renders, and the country simply
 * never appears — the one bug this data exists to prevent.
 */
describe("country silhouettes", () => {
  it("has a shape for every mapped jurisdiction", () => {
    const missing = Object.values(regulatoryData)
      .filter((c) => !COUNTRY_SHAPES[c.id])
      .map((c) => `${c.name} (${c.id})`);
    expect(missing).toEqual([]);
  });

  it("has no shapes for jurisdictions that are not mapped", () => {
    const orphans = Object.keys(COUNTRY_SHAPES).filter(
      (id) => !regulatoryData[id]
    );
    expect(orphans).toEqual([]);
  });

  it("pairs every shape with bounds", () => {
    for (const id of Object.keys(COUNTRY_SHAPES)) {
      expect(COUNTRY_BOUNDS[id], id).toBeDefined();
      expect(COUNTRY_BOUNDS[id], id).toHaveLength(4);
    }
  });

  it("draws only closed subpaths, so nothing renders as a stray line", () => {
    for (const [id, d] of Object.entries(COUNTRY_SHAPES)) {
      expect(d.startsWith("M"), id).toBe(true);
      expect(d.endsWith("Z"), id).toBe(true);
      // Every M must be terminated by a Z before the next one begins.
      expect(d.match(/M/g)?.length, id).toBe(d.match(/Z/g)?.length);
    }
  });

  it("keeps every shape inside the 512 box it is fitted to", () => {
    for (const [id, d] of Object.entries(COUNTRY_SHAPES)) {
      const nums = (d.match(/-?\d+(?:\.\d+)?/g) ?? []).map(Number);
      expect(nums.length, id).toBeGreaterThan(6);
      expect(Math.min(...nums), id).toBeGreaterThanOrEqual(-1);
      expect(Math.max(...nums), id).toBeLessThanOrEqual(513);
    }
  });

  it("gives each country bounds that actually contain its path", () => {
    for (const [id, d] of Object.entries(COUNTRY_SHAPES)) {
      const nums = (d.match(/-?\d+(?:\.\d+)?/g) ?? []).map(Number);
      const xs = nums.filter((_, i) => i % 2 === 0);
      const ys = nums.filter((_, i) => i % 2 === 1);
      const [bx, by, bw, bh] = COUNTRY_BOUNDS[id];
      expect(Math.min(...xs), id).toBeGreaterThanOrEqual(bx);
      expect(Math.max(...xs), id).toBeLessThanOrEqual(bx + bw);
      expect(Math.min(...ys), id).toBeGreaterThanOrEqual(by);
      expect(Math.max(...ys), id).toBeLessThanOrEqual(by + bh);
      expect(bw, id).toBeGreaterThan(0);
      expect(bh, id).toBeGreaterThan(0);
    }
  });

  it("uses at least one axis of the box, so no country is drawn small", () => {
    // fitSize fills one axis exactly; if neither is near 512 the shape was
    // fitted to geometry that is no longer being drawn.
    for (const [id, [, , w, h]] of Object.entries(COUNTRY_BOUNDS)) {
      expect(Math.max(w, h), id).toBeGreaterThan(500);
    }
  });
});
