import { describe, it, expect } from "vitest";
import { regulatoryData } from "@/app/data/regulatory-data";
import { COUNTRY_FRAMES } from "@/app/data/country-frames";
import { COUNTRY_DETAIL } from "@/app/data/country-detail";
import { DIVISION_PROFILES } from "@/app/data/divisions";
import { requirementsForDivision } from "@/app/data/requirements-data";

const W = 960;
const H = 520;

/**
 * country-frames.ts and country-detail.ts are generated by
 * scripts/build-country-detail.mjs and committed. Nothing runs the generator
 * automatically, so the failure mode is silent: add a jurisdiction, forget to
 * regenerate, and the camera falls back to the raw feature bounds — which is
 * exactly the bug the frames exist to fix, and it looks like a design choice
 * rather than a mistake.
 */
describe("map camera geometry", () => {
  it("frames every mapped jurisdiction", () => {
    const missing = Object.values(regulatoryData)
      .filter((c) => !COUNTRY_FRAMES[c.id])
      .map((c) => `${c.name} (${c.id})`);
    expect(missing).toEqual([]);
  });

  it("has a detail outline for every frame", () => {
    for (const id of Object.keys(COUNTRY_FRAMES)) {
      expect(COUNTRY_DETAIL[id], id).toBeTruthy();
    }
  });

  it("frames nothing that is not on the map", () => {
    const orphans = Object.keys(COUNTRY_FRAMES).filter((id) => !regulatoryData[id]);
    expect(orphans).toEqual([]);
  });

  it("keeps every frame inside the projection", () => {
    for (const [id, [x, y, w, h]] of Object.entries(COUNTRY_FRAMES)) {
      expect(w, id).toBeGreaterThan(0);
      expect(h, id).toBeGreaterThan(0);
      expect(x, id).toBeGreaterThanOrEqual(-1);
      expect(y, id).toBeGreaterThanOrEqual(-1);
      expect(x + w, id).toBeLessThanOrEqual(W + 1);
      expect(y + h, id).toBeLessThanOrEqual(H + 1);
    }
  });

  it("frames on principal landmasses, not the whole feature", () => {
    // The United States is the canonical failure: bounded including Alaska and
    // the Aleutians it is 844 of 960 units wide, which leaves the camera
    // nothing to do. Canada, France, Norway and the Netherlands fail the same
    // way. No frame should span more than half the world.
    for (const [id, [, , w]] of Object.entries(COUNTRY_FRAMES)) {
      expect(w, `${id} frame spans ${w} of ${W}`).toBeLessThan(W / 2);
    }
  });

  it("draws only closed subpaths", () => {
    for (const [id, d] of Object.entries(COUNTRY_DETAIL)) {
      expect(d.startsWith("M"), id).toBe(true);
      expect(d.endsWith("Z"), id).toBe(true);
      expect(d.match(/M/g)?.length, id).toBe(d.match(/Z/g)?.length);
    }
  });

  it("puts each detail outline inside its own frame", () => {
    for (const [id, d] of Object.entries(COUNTRY_DETAIL)) {
      const nums = (d.match(/-?\d+(?:\.\d+)?/g) ?? []).map(Number);
      const xs = nums.filter((_, i) => i % 2 === 0);
      const ys = nums.filter((_, i) => i % 2 === 1);
      const [fx, fy, fw, fh] = COUNTRY_FRAMES[id];
      // Half a unit of slack for the rounding the generator applies.
      expect(Math.min(...xs), id).toBeGreaterThanOrEqual(fx - 0.5);
      expect(Math.max(...xs), id).toBeLessThanOrEqual(fx + fw + 0.5);
      expect(Math.min(...ys), id).toBeGreaterThanOrEqual(fy - 0.5);
      expect(Math.max(...ys), id).toBeLessThanOrEqual(fy + fh + 0.5);
    }
  });
});

describe("the standard layer beside a jurisdiction", () => {
  it("has a profile for every division the requirement matrix uses", () => {
    for (const p of DIVISION_PROFILES) {
      expect(requirementsForDivision(p.division).length, `D${p.division}`).toBeGreaterThan(0);
    }
    expect(DIVISION_PROFILES.map((p) => p.division)).toEqual([1, 2, 3, 4, 5]);
  });
});
